package:
  name: coma
  version: 2.0.0

source:
  fn: meznom-coma-1cb288a988e3.tar.bz2
  url: https://bitbucket.org/meznom/coma/get/2.0.0.tar.bz2

requirements:
  build:
    - python
  run:
    - python

build:
  number: 0

test:
  requires:
    - numpy
    - ipython
    - pyzmq
  imports:
    - coma

about:
  home: https://bitbucket.org/meznom/coma
  license: BSD
  summary: A small Python library aiding with some aspects of running computer simulations
