# Adpated from https://github.com/conda/conda-recipes/tree/master/boost
package:
  name: boost-test
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2

build:
  number: 0

requirements:
  build:
    - python

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost Unit Test Library from the Boost C++ Libraries collection
